Will never save an empty mirrorlist again.

diff --git a/scripts/upmirror b/scripts/upmirror
--- a/scripts/upmirror
+++ b/scripts/upmirror
@@ -17,8 +17,8 @@ function check_deps () {
 
 # If dependencies are not installed, try to install them.
 check_deps
-if ! [ -z $INSTALL ]; then
-    if [ $EUID -ne 0 ]; then
+if ! [[ -z $INSTALL ]]; then
+    if [[ $EUID -ne 0 ]]; then
         echo "Need to install dependencies and you're not root. Bye."
         exit
     fi
@@ -29,7 +29,7 @@ fi
 
 # See that dependencies were installed and are executable.
 check_deps
-if ! [ -z $INSTALL ]; then
+if ! [[ -z $INSTALL ]]; then
     echo "Dependencies are either not installed or not executable. Bye."
     exit
 fi
@@ -37,16 +37,16 @@ fi
 # Check if root,
 # check if /etc/pacman.d exists
 # check if we need to backup the old mirrorlist.
-if [ $EUID -ne 0 ]; then
-    echo "Not root. Saving new mirrors to ~/mirrors."
+if [[ $EUID -ne 0 ]]; then
+    echo "Not root. Saving new mirrors to ~/mirrorlist."
     MIRROR_PATH="$HOME"
 
 else
-    if [ -d /etc/pacman.d ]; then
+    if [[ -d /etc/pacman.d ]]; then
         echo "Running as root, your current mirror list will be replaced."
         MIRROR_PATH="/etc/pacman.d/"
 
-        if [ -e /etc/pacman.d/mirrorlist ]; then
+        if [[ -e /etc/pacman.d/mirrorlist ]]; then
             echo "A backup will be created at /etc/pacman.d/mirrorlist_old."
             mv "$MIRROR_PATH/mirrorlist" "$MIRROR_PATH/mirrorlist_old"
         fi
@@ -67,8 +67,13 @@ country=DE\
 &protocol=https&use_mirror_status=on" 
 
 # Download new mirrors and test them for speed.
-curl -s $URL |
+NEW_FILE=$(curl -s $URL |
     sed -e 's/^#Server/Server/' -e '/^#/d' |
-    rankmirrors -n 30 - >> $MIRROR_PATH/mirrorlist
+    rankmirrors -n 30 -) 
 
-
+if ! [[ -z $NEW_FILE ]]; then
+    printf "$NEW_FILE" > $MIRROR_PATH/mirrorlist
+else
+    echo
+    echo "Error! New mirror file was empty, not saving to file."
+fi
